### ISSUE TITLE
When open new buffer (without save as file), lsp show error message 

### ISSUE THREAD

**Issue by vuquangtam** [emacs-lsp/lsp-mode#1930]
**Describe the bug**
When open new buffer (without save as file), lsp show error message 

**To Reproduce**
Create new buffer: test.js.
It shows: File mode specification error: (file-missing Opening input file No such file or directory ./code/test.js)

**Expected behavior**
Don't show error when open new buffer

**Which Language Server did you use**
lsp-typescript, lsp-angular, lsp-ruby

**OS**
Ubuntu 18.04

**Comment by yyoncho** [comment]
which version of lsp-mode do you use? This should have been fixed with 58f14fed. If you are using the latest lsp-mode version please provide callstack as described in bug template.

**Comment by vuquangtam** [comment]
> which version of lsp-mode do you use? This should have been fixed with [58f14fe](https://github.com/emacs-lsp/lsp-mode/commit/58f14fed708c7e04c7be9653307ee0c3745fe204). If you are using the latest lsp-mode version please provide callstack as described in bug template.

Hi, I'm using version 7.0, it's still show the error message:
"File mode specification error: (file-missing Opening input file No such file or directory ./code/test.js)"

**Comment by yyoncho** [comment]
Ok, can you provide requested info?

**Comment by vuquangtam** [comment]
Here the info

**Error callstack**
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  remhash("/home/lap13180/test-lsp.js" nil)
  lsp--on-diagnostics(#s(lsp--workspace :ewoc #s(ewoc :buffer #<buffer *lsp-log: ts-ls:13288*> :pretty-printer lsp--log-entry-pp :header [[[[... #5 ... #<marker at 7644 in *lsp-log: ts-ls:13288*>] #4 "" #<marker at 7803 in *lsp-log: ts-ls:13288*>] #3 DL-LIST #<marker at 7803 in *lsp-log: ts-ls:13288*>] [#3 [#4 [#5 ... ... #<marker at 5298 in *lsp-log: ts-ls:13288*>] #s(lsp--log-entry :timestamp "02:32:05 PM" :process-time 168 :type incoming-resp :method "initialize" :id 22 :body #<hash-table equal 2/2 0x156d381671f9>) #<marker at 4110 in *lsp-log: ts-ls:13288*>] #s(lsp--log-entry :timestamp "02:32:05 PM" :process-time nil :type outgoing-req :method "initialize" :id 22 :body (:processId nil :rootPath "/home/lap13180" :clientInfo ... :rootUri "file:///home/lap13180" :capabilities ... :initializationOptions ... :workDoneToken "1")) #<marker at 1 in *lsp-log: ts-ls:13288*>] "" #<marker at 1 in *lsp-log: ts-ls:13288*>] :footer [[[[... #5 ... #<marker at 7496 in *lsp-log: ts-ls:13288*>] #4 #s(lsp--log-entry :timestamp "02:32:09 PM" :process-time 0 :type incoming-resp :method nil :id 26 :body ...) #<marker at 7570 in *lsp-log: ts-ls:13288*>] #3 #s(lsp--log-entry :timestamp "02:32:09 PM" :process-time nil :type incoming-notif :method "textDocument/publishDiagnostics" :id nil :body #<hash-table equal 2/2 0x156d3a0496d1>) #<marker at 7644 in *lsp-log: ts-ls:13288*>] [#3 [#4 [#5 ... ... #<marker at 1 in *lsp-log: ts-ls:13288*>] "" #<marker at 1 in *lsp-log: ts-ls:13288*>] DL-LIST #<marker at 7803 in *lsp-log: ts-ls:13288*>] "" #<marker at 7803 in *lsp-log: ts-ls:13288*>] :dll [[[[... #5 ... #<marker at 7570 in *lsp-log: ts-ls:13288*>] #4 #s(lsp--log-entry :timestamp "02:32:09 PM" :process-time nil :type incoming-notif :method "textDocument/publishDiagnostics" :id nil :body #<hash-table equal 2/2 0x156d3a0496d1>) #<marker at 7644 in *lsp-log: ts-ls:13288*>] #3 "" #<marker at 7803 in *lsp-log: ts-ls:13288*>] [#3 [#4 [#5 ... ... #<marker at 4110 in *lsp-log: ts-ls:13288*>] #s(lsp--log-entry :timestamp "02:32:05 PM" :process-time nil :type outgoing-req :method "initialize" :id 22 :body ...) #<marker at 1 in *lsp-log: ts-ls:13288*>] "" #<marker at 1 in *lsp-log: ts-ls:13288*>] DL-LIST #<marker at 7803 in *lsp-log: ts-ls:13288*>] :last-node nil :hf-pp insert) :server-capabilities #<hash-table equal 17/17 0x156d3816724d> :registered-server-capabilities nil :root "/home/lap13180" :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn) #<bytecode 0x156d3794a395>) :test\? #f(compiled-function () #<bytecode 0x156d3794b9ad>)) :ignore-regexps nil :ignore-messages ("readFile .*? requested by TypeScript but con...") :notification-handlers #<hash-table equal 0/65 0x156d3794bf31> :request-handlers #<hash-table equal 0/65 0x156d3794c161> :response-handlers #<hash-table eql 0/65 0x156d3794c181> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x156d3794c7f5> :action-handlers #<hash-table equal 0/65 0x156d3794caed> :major-modes nil :activation-fn lsp-typescript-javascript-tsx-jsx-activate-p :priority -2 :server-id ts-ls :multi-root nil :initialization-options #f(compiled-function () #<bytecode 0x156d3794a1e5>) :custom-capabilities nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? t :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn nil :async-request-handlers #<hash-table equal 0/65 0x156d3794cd1d> :download-server-fn #f(compiled-function (client callback error-callback update\?) #<bytecode 0x156d3794a1fd>) :download-in-progress? nil :buffers nil) :host-root nil :proc #<process ts-ls<1>> :cmd-proc #<process ts-ls<1>> :buffers nil :semantic-highlighting-faces nil :semantic-highlighting-modifier-faces nil :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x156d37fd0669> :watches #<hash-table equal 0/65 0x156d37fd0899> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 0/65 0x156d37fd08b9> :work-done-tokens #<hash-table equal 0/65 0x156d37fd08d9>) #<hash-table equal 2/2 0x156d383f556d>)
  lsp--on-notification(#s(lsp--workspace :ewoc #s(ewoc :buffer #<buffer *lsp-log: ts-ls:13288*> :pretty-printer lsp--log-entry-pp :header [[[[... #5 ... #<marker at 7644 in *lsp-log: ts-ls:13288*>] #4 "" #<marker at 7803 in *lsp-log: ts-ls:13288*>] #3 DL-LIST #<marker at 7803 in *lsp-log: ts-ls:13288*>] [#3 [#4 [#5 ... ... #<marker at 5298 in *lsp-log: ts-ls:13288*>] #s(lsp--log-entry :timestamp "02:32:05 PM" :process-time 168 :type incoming-resp :method "initialize" :id 22 :body #<hash-table equal 2/2 0x156d381671f9>) #<marker at 4110 in *lsp-log: ts-ls:13288*>] #s(lsp--log-entry :timestamp "02:32:05 PM" :process-time nil :type outgoing-req :method "initialize" :id 22 :body (:processId nil :rootPath "/home/lap13180" :clientInfo ... :rootUri "file:///home/lap13180" :capabilities ... :initializationOptions ... :workDoneToken "1")) #<marker at 1 in *lsp-log: ts-ls:13288*>] "" #<marker at 1 in *lsp-log: ts-ls:13288*>] :footer [[[[... #5 ... #<marker at 7496 in *lsp-log: ts-ls:13288*>] #4 #s(lsp--log-entry :timestamp "02:32:09 PM" :process-time 0 :type incoming-resp :method nil :id 26 :body ...) #<marker at 7570 in *lsp-log: ts-ls:13288*>] #3 #s(lsp--log-entry :timestamp "02:32:09 PM" :process-time nil :type incoming-notif :method "textDocument/publishDiagnostics" :id nil :body #<hash-table equal 2/2 0x156d3a0496d1>) #<marker at 7644 in *lsp-log: ts-ls:13288*>] [#3 [#4 [#5 ... ... #<marker at 1 in *lsp-log: ts-ls:13288*>] "" #<marker at 1 in *lsp-log: ts-ls:13288*>] DL-LIST #<marker at 7803 in *lsp-log: ts-ls:13288*>] "" #<marker at 7803 in *lsp-log: ts-ls:13288*>] :dll [[[[... #5 ... #<marker at 7570 in *lsp-log: ts-ls:13288*>] #4 #s(lsp--log-entry :timestamp "02:32:09 PM" :process-time nil :type incoming-notif :method "textDocument/publishDiagnostics" :id nil :body #<hash-table equal 2/2 0x156d3a0496d1>) #<marker at 7644 in *lsp-log: ts-ls:13288*>] #3 "" #<marker at 7803 in *lsp-log: ts-ls:13288*>] [#3 [#4 [#5 ... ... #<marker at 4110 in *lsp-log: ts-ls:13288*>] #s(lsp--log-entry :timestamp "02:32:05 PM" :process-time nil :type outgoing-req :method "initialize" :id 22 :body ...) #<marker at 1 in *lsp-log: ts-ls:13288*>] "" #<marker at 1 in *lsp-log: ts-ls:13288*>] DL-LIST #<marker at 7803 in *lsp-log: ts-ls:13288*>] :last-node nil :hf-pp insert) :server-capabilities #<hash-table equal 17/17 0x156d3816724d> :registered-server-capabilities nil :root "/home/lap13180" :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn) #<bytecode 0x156d3794a395>) :test\? #f(compiled-function () #<bytecode 0x156d3794b9ad>)) :ignore-regexps nil :ignore-messages ("readFile .*? requested by TypeScript but con...") :notification-handlers #<hash-table equal 0/65 0x156d3794bf31> :request-handlers #<hash-table equal 0/65 0x156d3794c161> :response-handlers #<hash-table eql 0/65 0x156d3794c181> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x156d3794c7f5> :action-handlers #<hash-table equal 0/65 0x156d3794caed> :major-modes nil :activation-fn lsp-typescript-javascript-tsx-jsx-activate-p :priority -2 :server-id ts-ls :multi-root nil :initialization-options #f(compiled-function () #<bytecode 0x156d3794a1e5>) :custom-capabilities nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? t :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn nil :async-request-handlers #<hash-table equal 0/65 0x156d3794cd1d> :download-server-fn #f(compiled-function (client callback error-callback update\?) #<bytecode 0x156d3794a1fd>) :download-in-progress? nil :buffers nil) :host-root nil :proc #<process ts-ls<1>> :cmd-proc #<process ts-ls<1>> :buffers nil :semantic-highlighting-faces nil :semantic-highlighting-modifier-faces nil :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x156d37fd0669> :watches #<hash-table equal 0/65 0x156d37fd0899> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 0/65 0x156d37fd08b9> :work-done-tokens #<hash-table equal 0/65 0x156d37fd08d9>) #<hash-table equal 3/3 0x156d383f5515>)
  lsp--parser-on-message(#<hash-table equal 3/3 0x156d383f5515> #s(lsp--workspace :ewoc #s(ewoc :buffer #<buffer *lsp-log: ts-ls:13288*> :pretty-printer lsp--log-entry-pp :header [[[[... #6 ... #<marker at 7644 in *lsp-log: ts-ls:13288*>] #5 "" #<marker at 7803 in *lsp-log: ts-ls:13288*>] #4 DL-LIST #<marker at 7803 in *lsp-log: ts-ls:13288*>] [#4 [#5 [#6 ... ... #<marker at 5298 in *lsp-log: ts-ls:13288*>] #s(lsp--log-entry :timestamp "02:32:05 PM" :process-time 168 :type incoming-resp :method "initialize" :id 22 :body #<hash-table equal 2/2 0x156d381671f9>) #<marker at 4110 in *lsp-log: ts-ls:13288*>] #s(lsp--log-entry :timestamp "02:32:05 PM" :process-time nil :type outgoing-req :method "initialize" :id 22 :body (:processId nil :rootPath "/home/lap13180" :clientInfo ... :rootUri "file:///home/lap13180" :capabilities ... :initializationOptions ... :workDoneToken "1")) #<marker at 1 in *lsp-log: ts-ls:13288*>] "" #<marker at 1 in *lsp-log: ts-ls:13288*>] :footer [[[[... #6 ... #<marker at 7496 in *lsp-log: ts-ls:13288*>] #5 #s(lsp--log-entry :timestamp "02:32:09 PM" :process-time 0 :type incoming-resp :method nil :id 26 :body ...) #<marker at 7570 in *lsp-log: ts-ls:13288*>] #4 #s(lsp--log-entry :timestamp "02:32:09 PM" :process-time nil :type incoming-notif :method "textDocument/publishDiagnostics" :id nil :body #<hash-table equal 2/2 0x156d3a0496d1>) #<marker at 7644 in *lsp-log: ts-ls:13288*>] [#4 [#5 [#6 ... ... #<marker at 1 in *lsp-log: ts-ls:13288*>] "" #<marker at 1 in *lsp-log: ts-ls:13288*>] DL-LIST #<marker at 7803 in *lsp-log: ts-ls:13288*>] "" #<marker at 7803 in *lsp-log: ts-ls:13288*>] :dll [[[[... #6 ... #<marker at 7570 in *lsp-log: ts-ls:13288*>] #5 #s(lsp--log-entry :timestamp "02:32:09 PM" :process-time nil :type incoming-notif :method "textDocument/publishDiagnostics" :id nil :body #<hash-table equal 2/2 0x156d3a0496d1>) #<marker at 7644 in *lsp-log: ts-ls:13288*>] #4 "" #<marker at 7803 in *lsp-log: ts-ls:13288*>] [#4 [#5 [#6 ... ... #<marker at 4110 in *lsp-log: ts-ls:13288*>] #s(lsp--log-entry :timestamp "02:32:05 PM" :process-time nil :type outgoing-req :method "initialize" :id 22 :body ...) #<marker at 1 in *lsp-log: ts-ls:13288*>] "" #<marker at 1 in *lsp-log: ts-ls:13288*>] DL-LIST #<marker at 7803 in *lsp-log: ts-ls:13288*>] :last-node nil :hf-pp insert) :server-capabilities #<hash-table equal 17/17 0x156d3816724d> :registered-server-capabilities nil :root "/home/lap13180" :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn) #<bytecode 0x156d3794a395>) :test\? #Command "/home/lap13180/.emacs.d/.cache/lsp/npm/javascript-typescript-langserver/bin/javascript-typescript-stdio" is present on the path.
Command "/home/lap13180/.nvm/versions/node/v10.20.1/bin/typescript-language-server --tsserver-path /home/lap13180/.nvm/versions/node/v10.20.1/bin/tsserver --stdio" is present on the path.
Command "/home/lap13180/.emacs.d/.cache/lsp/npm/javascript-typescript-langserver/bin/javascript-typescript-stdio" is present on the path.
Command "/home/lap13180/.nvm/versions/node/v10.20.1/bin/typescript-language-server --tsserver-path /home/lap13180/.nvm/versions/node/v10.20.1/bin/tsserver --stdio" is present on the path.
Found the following clients for /home/lap13180/.working/company/zalo-ads-v2/src/app/modules/form/shared/components/form-list/form-list.component.ts: (server-id jsts-ls, priority -3), (server-id ts-ls, priority -2)
The following clients were selected based on priority: (server-id ts-ls, priority -2)
Command "/home/lap13180/.emacs.d/.cache/lsp/npm/javascript-typescript-langserver/bin/javascript-typescript-stdio" is present on the path.
Command "/home/lap13180/.nvm/versions/node/v10.20.1/bin/typescript-language-server --tsserver-path /home/lap13180/.nvm/versions/node/v10.20.1/bin/tsserver --stdio" is present on the path.
Command "/home/lap13180/.emacs.d/.cache/lsp/npm/vscode-html-languageserver-bin/bin/html-languageserver --stdio" is present on the path.
Command "/home/lap13180/.emacs.d/.cache/lsp/npm/javascript-typescript-langserver/bin/javascript-typescript-stdio" is present on the path.
Command "/home/lap13180/.nvm/versions/node/v10.20.1/bin/typescript-language-server --tsserver-path /home/lap13180/.nvm/versions/node/v10.20.1/bin/tsserver --stdio" is present on the path.
Command "/home/lap13180/.emacs.d/.cache/lsp/npm/vscode-html-languageserver-bin/bin/html-languageserver --stdio" is present on the path.
Found the following clients for /home/lap13180/test-lsp.js: (server-id jsts-ls, priority -3), (server-id ts-ls, priority -2), (server-id html-ls, priority -4)
The following clients were selected based on priority: (server-id ts-ls, priority -2)
Cancelling textDocument/codeAction(26) in hook post-command-hook
Cancelling textDocument/documentHighlight(25) in hook kill-buffer-hook
f(compiled-function () #<bytecode 0x156d3794b9ad>)) :ignore-regexps nil :ignore-messages ("readFile .*? requested by TypeScript but con...") :notification-handlers #<hash-table equal 0/65 0x156d3794bf31> :request-handlers #<hash-table equal 0/65 0x156d3794c161> :response-handlers #<hash-table eql 0/65 0x156d3794c181> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x156d3794c7f5> :action-handlers #<hash-table equal 0/65 0x156d3794caed> :major-modes nil :activation-fn lsp-typescript-javascript-tsx-jsx-activate-p :priority -2 :server-id ts-ls :multi-root nil :initialization-options #f(compiled-function () #<bytecode 0x156d3794a1e5>) :custom-capabilities nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? t :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn nil :async-request-handlers #<hash-table equal 0/65 0x156d3794cd1d> :download-server-fn #f(compiled-function (client callback error-callback update\?) #<bytecode 0x156d3794a1fd>) :download-in-progress? nil :buffers nil) :host-root nil :proc #<process ts-ls<1>> :cmd-proc #<process ts-ls<1>> :buffers nil :semantic-highlighting-faces nil :semantic-highlighting-modifier-faces nil :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x156d37fd0669> :watches #<hash-table equal 0/65 0x156d37fd0899> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 0/65 0x156d37fd08b9> :work-done-tokens #<hash-table equal 0/65 0x156d37fd08d9>))
  #f(compiled-function (proc input) #<bytecode 0x156d37fd1f59>)(#<process ts-ls<1>> "Content-Length: 130\15\n\15\n{\"jsonrpc\":\"2.0\",\"method\":\"...")

**lsp-log**
Command "/home/lap13180/.emacs.d/.cache/lsp/npm/javascript-typescript-langserver/bin/javascript-typescript-stdio" is present on the path.
Command "/home/lap13180/.nvm/versions/node/v10.20.1/bin/typescript-language-server --tsserver-path /home/lap13180/.nvm/versions/node/v10.20.1/bin/tsserver --stdio" is present on the path.
Command "/home/lap13180/.emacs.d/.cache/lsp/npm/javascript-typescript-langserver/bin/javascript-typescript-stdio" is present on the path.
Command "/home/lap13180/.nvm/versions/node/v10.20.1/bin/typescript-language-server --tsserver-path /home/lap13180/.nvm/versions/node/v10.20.1/bin/tsserver --stdio" is present on the path.
Found the following clients for /home/lap13180/.working/company/zalo-ads-v2/src/app/modules/form/shared/components/form-list/form-list.component.ts: (server-id jsts-ls, priority -3), (server-id ts-ls, priority -2)
The following clients were selected based on priority: (server-id ts-ls, priority -2)
Command "/home/lap13180/.emacs.d/.cache/lsp/npm/javascript-typescript-langserver/bin/javascript-typescript-stdio" is present on the path.
Command "/home/lap13180/.nvm/versions/node/v10.20.1/bin/typescript-language-server --tsserver-path /home/lap13180/.nvm/versions/node/v10.20.1/bin/tsserver --stdio" is present on the path.
Command "/home/lap13180/.emacs.d/.cache/lsp/npm/vscode-html-languageserver-bin/bin/html-languageserver --stdio" is present on the path.
Command "/home/lap13180/.emacs.d/.cache/lsp/npm/javascript-typescript-langserver/bin/javascript-typescript-stdio" is present on the path.
Command "/home/lap13180/.nvm/versions/node/v10.20.1/bin/typescript-language-server --tsserver-path /home/lap13180/.nvm/versions/node/v10.20.1/bin/tsserver --stdio" is present on the path.
Command "/home/lap13180/.emacs.d/.cache/lsp/npm/vscode-html-languageserver-bin/bin/html-languageserver --stdio" is present on the path.
Found the following clients for /home/lap13180/test-lsp.js: (server-id jsts-ls, priority -3), (server-id ts-ls, priority -2), (server-id html-ls, priority -4)
The following clients were selected based on priority: (server-id ts-ls, priority -2)
Cancelling textDocument/codeAction(26) in hook post-command-hook
Cancelling textDocument/documentHighlight(25) in hook kill-buffer-hook


**lsp-log ts-ls*
[Trace - 02:32:05 PM] Sending request 'initialize - (22)'.
Params: {
  "processId": null,
  "rootPath": "/home/lap13180",
  "clientInfo": {
    "name": "emacs",
    "version": "GNU Emacs 27.0.91 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30, cairo version 1.15.10)\n of 2020-07-15"
  },
  "rootUri": "file:///home/lap13180",
  "capabilities": {
    "workspace": {
      "workspaceEdit": {
        "documentChanges": true,
        "resourceOperations": [
          "create",
          "rename",
          "delete"
        ]
      },
      "applyEdit": true,
      "symbol": {
        "symbolKind": {
          "valueSet": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26
          ]
        }
      },
      "executeCommand": {
        "dynamicRegistration": false
      },
      "didChangeWatchedFiles": {
        "dynamicRegistration": true
      },
      "workspaceFolders": true,
      "configuration": true
    },
    "textDocument": {
      "declaration": {
        "linkSupport": true
      },
      "definition": {
        "linkSupport": true
      },
      "implementation": {
        "linkSupport": true
      },
      "typeDefinition": {
        "linkSupport": true
      },
      "synchronization": {
        "willSave": true,
        "didSave": true,
        "willSaveWaitUntil": true
      },
      "documentSymbol": {
        "symbolKind": {
          "valueSet": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26
          ]
        },
        "hierarchicalDocumentSymbolSupport": true
      },
      "formatting": {
        "dynamicRegistration": true
      },
      "rangeFormatting": {
        "dynamicRegistration": true
      },
      "rename": {
        "dynamicRegistration": true,
        "prepareSupport": true
      },
      "codeAction": {
        "dynamicRegistration": true,
        "isPreferredSupport": true,
        "codeActionLiteralSupport": {
          "codeActionKind": {
            "valueSet": [
              "",
              "quickfix",
              "refactor",
              "refactor.extract",
              "refactor.inline",
              "refactor.rewrite",
              "source",
              "source.organizeImports"
            ]
          }
        }
      },
      "completion": {
        "completionItem": {
          "snippetSupport": true,
          "documentationFormat": [
            "markdown"
          ]
        },
        "contextSupport": true
      },
      "signatureHelp": {
        "signatureInformation": {
          "parameterInformation": {
            "labelOffsetSupport": true
          }
        }
      },
      "documentLink": {
        "dynamicRegistration": true,
        "tooltipSupport": true
      },
      "hover": {
        "contentFormat": [
          "markdown",
          "plaintext"
        ]
      },
      "foldingRange": {
        "dynamicRegistration": true
      },
      "callHierarchy": {
        "dynamicRegistration": false
      },
      "publishDiagnostics": {
        "relatedInformation": true,
        "tagSupport": {
          "valueSet": [
            1,
            2
          ]
        },
        "versionSupport": true
      }
    },
    "window": {
      "workDoneProgress": true
    }
  },
  "initializationOptions": {
    "plugins": [],
    "logVerbosity": "info",
    "tsServerPath": "/home/lap13180/.nvm/versions/node/v10.20.1/bin/tsserver"
  },
  "workDoneToken": "1"
}


[Trace - 02:32:05 PM] Received response 'initialize - (22)' in 168ms.
Result: {
  "logFileUri": "file:///home/lap13180/.log/tsserver.log",
  "capabilities": {
    "callsProvider": true,
    "foldingRangeProvider": true,
    "typeDefinitionProvider": true,
    "implementationProvider": true,
    "workspaceSymbolProvider": true,
    "signatureHelpProvider": {
      "triggerCharacters": [
        "(",
        ",",
        "<"
      ]
    },
    "referencesProvider": true,
    "renameProvider": true,
    "hoverProvider": true,
    "executeCommandProvider": {
      "commands": [
        "_typescript.applyWorkspaceEdit",
        "_typescript.applyCodeAction",
        "_typescript.applyRefactoring",
        "_typescript.organizeImports",
        "_typescript.applyRenameFile"
      ]
    },
    "documentSymbolProvider": true,
    "documentHighlightProvider": true,
    "documentFormattingProvider": true,
    "definitionProvider": true,
    "codeActionProvider": true,
    "completionProvider": {
      "resolveProvider": true,
      "triggerCharacters": [
        ".",
        "\"",
        "'",
        "/",
        "@",
        "<"
      ]
    },
    "textDocumentSync": 2
  }
}


[Trace - 02:32:05 PM] Sending notification 'initialized'.
Params: {
}


[Trace - 02:32:05 PM] Sending notification 'textDocument/didOpen'.
Params: {
  "textDocument": {
    "uri": "file:///home/lap13180/test-lsp.js",
    "languageId": "html",
    "version": 0,
    "text": ""
  }
}


[Trace - 02:32:05 PM] Sending request 'textDocument/documentHighlight - (23)'.
Params: {
  "textDocument": {
    "uri": "file:///home/lap13180/test-lsp.js"
  },
  "position": {
    "line": 0,
    "character": 0
  }
}


[Trace - 02:32:05 PM] Sending request 'textDocument/codeAction - (24)'.
Params: {
  "textDocument": {
    "uri": "file:///home/lap13180/test-lsp.js"
  },
  "range": {
    "start": {
      "line": 0,
      "character": 0
    },
    "end": {
      "line": 0,
      "character": 0
    }
  },
  "context": {
    "diagnostics": []
  }
}


[Trace - 02:32:06 PM] Sending notification '$/cancelRequest'.
Params: {
  "id": 23
}


[Trace - 02:32:06 PM] Sending request 'textDocument/documentHighlight - (25)'.
Params: {
  "textDocument": {
    "uri": "file:///home/lap13180/test-lsp.js"
  },
  "position": {
    "line": 0,
    "character": 0
  }
}


[Trace - 02:32:06 PM] Sending notification '$/cancelRequest'.
Params: {
  "id": 24
}


[Trace - 02:32:06 PM] Sending request 'textDocument/codeAction - (26)'.
Params: {
  "textDocument": {
    "uri": "file:///home/lap13180/test-lsp.js"
  },
  "range": {
    "start": {
      "line": 0,
      "character": 0
    },
    "end": {
      "line": 0,
      "character": 0
    }
  },
  "context": {
    "diagnostics": []
  }
}


[Trace - 02:32:07 PM] Sending notification '$/cancelRequest'.
Params: {
  "id": 26
}


[Trace - 02:32:07 PM] Sending notification '$/cancelRequest'.
Params: {
  "id": 25
}


[Trace - 02:32:07 PM] Sending notification 'textDocument/didClose'.
Params: {
  "textDocument": {
    "uri": "file:///home/lap13180/test-lsp.js"
  }
}


[Trace - 02:32:07 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
  "diagnostics": [],
  "uri": "file:///home/lap13180/test-lsp.js"
}


[Trace - 02:32:09 PM] Received response 'nil - (23)' in 0ms.
Result: []


[Trace - 02:32:09 PM] Received response 'nil - (25)' in 0ms.
Result: []


[Trace - 02:32:09 PM] Received response 'nil - (24)' in 0ms.
Result: []


[Trace - 02:32:09 PM] Received response 'nil - (26)' in 0ms.
Result: []


[Trace - 02:32:09 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
  "diagnostics": [],
  "uri": "file:///home/lap13180/test-lsp.js"
}

**Comment by yyoncho** [comment]
Can you try deleting lsp-mode package, restarting emacs and then installing it again?

**Comment by vuquangtam** [comment]
> Can you try deleting lsp-mode package, restarting emacs and then installing it again?

It works. Thank you very much for quick support
