### ISSUE TITLE
Something weird with flycheck in lsp-mode

### ISSUE THREAD

**Issue by samrayleung** [emacs-lsp/lsp-mode#246]
I have another issue when I use `lsp-mode`. I don't know why  I open Rust file with `lsp-mode`and `lsp-rust`, everything works fine,but once I start edit my file, all flycheck errors/warnings disappear(I mean it disappears permanently until I restart Emacs), it is so weird: please pay attention to the `mode-line`, `FC` means `flycheck`:

![peek 2018-01-20 20-09](https://user-images.githubusercontent.com/14180681/35183291-6660a22c-fe1e-11e7-9058-6c6c32293097.gif)
 
This is my configuration about `lsp-mode`, but it seems it is nothing to do with my configuration: 
```elisp
(use-package lsp-mode
  :ensure t
  :defer t
  :config (progn
	    (require 'lsp-flycheck)
	    (add-hook 'python-mode-hook 'lsp-mode)
	    (add-hook 'rust-mode-hook 'lsp-mode)
	    (set-face-attribute 'lsp-face-highlight-textual nil
				:background "#666" :foreground "#ffffff"
				)
	    ))
(use-package lsp-python
  :ensure t
  :config(progn
	   (add-hook 'python-mode-hook 'lsp-python-enable)
	   ))
(use-package lsp-rust
  :ensure t
  :config (progn
	    (require 'lsp-flycheck)
	    (require 'lsp-mode)
	    (add-hook 'rust-mode-hook 'lsp-rust-enable)
	    (add-hook 'rust-mode-hook 'flycheck-mode)
	    ))

```

**Comment by sebastiencs** [comment]
It's a bug in the RLS. It has been fixed with https://github.com/rust-lang-nursery/rls/pull/661

**Comment by samrayleung** [comment]
It seems my toolchain is up to date, the result of `rustup update`:
```
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.25.0-nightly (5965b7901 2018-01-19)
```
But the flycheck warnings/errors still disappear, are there some missing steps?

**Comment by sebastiencs** [comment]
It depends how did you installed the RLS, with rustup ?

I recommend you to build the rls yourself and configure `lsp-rust` like that:
```el

(use-package lsp-rust
  :hook (rust-mode . lsp-rust-enable)
  :bind ("M-#" . my-lsp-rust-find-implementations)
  :init
  (defun my-lsp-rust-find-implementations ()
    (interactive)
    (lsp-ui-peek-find-custom 'implementations "rustDocument/implementations"))
  :config
  (setenv "LD_LIBRARY_PATH" "/home/sebastien/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/")
  (setq lsp-rust-rls-command "/home/sebastien/github/rls/target/release/rls"))

```

**Comment by samrayleung** [comment]
Yes, I install RLS with rustup. I will try to build RLS by myself, and send some feedback later.
By the way, maybe you could set your `LD_LIBRARY_PATH` with this function:
```elisp
(defun my/set-rust-ld-library-path ()
    (let* ((command (concat "rustc --print sysroot"))
	 (rustc-sysroot-path (shell-command-to-string command))
	 (strip-path (replace-regexp-in-string "\n$" "" rustc-sysroot-path)))
    (if (eq system-type 'windows-nt)
	(concat strip-path "\\lib\\")
      (concat strip-path "/lib/"))))
(setenv "LD_LIBRARY_PATH" (my/set-rust-ld-library-path))
```
IMHO, it's more flexible rather than hard-code

**Comment by samrayleung** [comment]
I clone `RLS` repo and build with `cargo build --release`. After I build `RLS` by mysel, I could not get `RLS` work. this is the backtrace message:
```
Debugger entered--Lisp error: (error "lsp-rust: Cannot communicate with the process (exit)")
  signal(error ("lsp-rust: Cannot communicate with the process (exit)"))
  error("%s: Cannot communicate with the process (%s)" "lsp-rust" exit)
  lsp--send-no-wait("Content-Length: 19983
\n
\n{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/didOpen\",\"params\":{\"textDocument\":{\"uri\":\"file:///home/samray/Code/rust/rspotify/src/spotify/oauth2.rs\",\"languageId\":\"rust\",\"version\":0,\"text\":\"// use 3rd party library\\nuse chrono::prelude::*;\\nuse serde_json;\\nuse reqwest::Client;\\nuse reqwest::header::{Authorization, Basic, Bearer};\\nuse dotenv::dotenv;\\nuse percent_encoding::{utf8_percent_encode, PATH_SEGMENT_ENCODE_SET};\\nuse url::Url;\\n\\n// use built-in library\\nuse std::env;\\nuse std::collections::{HashMap, HashSet};\\nuse std::path::{Path, PathBuf};\\nuse std::error::Error;\\nuse std::fs::File;\\nuse std::iter::FromIterator;\\nuse std::io::prelude::*;\\nuse std::fs::OpenOptions;\\n\\n// use customized library\\nuse super::util::{convert_map_to_string, datetime_to_timestamp, generate_random_string};\\npub struct SpotifyClientCredentials {\\n    pub client_id: String,\\n    pub client_secret: String,\\n    pub token_info: Option<TokenInfo>,\\n}\\n#[derive(Clone, Debug, Serialize, Deserialize)]\\npub struct SpotifyOAuth {\\n    pub client_id: String,\\n    pub client_secret: String,\\n    pub redirect_uri: String,\\n    pub state: String,\\n    pub cache_path: PathBuf,\\n    pub scope: String,\\n    pub proxies: Option<String>,\\n}\\n#[derive(Debug)]\\npub enum SpotifyAuthError {\\n    AuthorizateError,\\n    FileHandleError,\\n}\\n\\n#[derive(Clone, Debug, Serialize, Deserialize)]\\npub struct TokenInfo {\\n    pub access_token: String,\\n    pub token_type: String,\\n    pub expires_in: u32,\\n    pub expires_at: Option<i64>,\\n    pub refresh_token: Option<String>,\\n    pub scope: String,\\n}\\nimpl TokenInfo {\\n    pub fn new() -> TokenInfo {\\n        TokenInfo {\\n            access_token: String::new(),\\n            token_type: String::new(),\\n            expires_in: 0u32,\\n            expires_at: None,\\n            refresh_token: None,\\n            scope: String::new(),\\n        }\\n    }\\n    pub fn access_token(mut self, access_token: &str) -> TokenInfo {\\n        self.access_token = access_token.to_owned();\\n        self\\n    }\\n    pub fn token_type(mut self, token_type: &str) -> TokenInfo {\\n        self.token_type = token_type.to_owned();\\n        self\\n    }\\n    pub fn expires_in(mut self, expires_in: u32) -> TokenInfo {\\n        self.expires_in = expires_in;\\n        self\\n    }\\n    pub fn scope(mut self, scope: &str) -> TokenInfo {\\n        self.scope = scope.to_owned();\\n        self\\n    }\\n    pub fn expires_at(mut self, expires_at: i64) -> TokenInfo {\\n        self.expires_at = Some(expires_at);\\n        self\\n    }\\n    pub fn refresh_token(mut self, refresh_token: &str) -> TokenInfo {\\n        self.refresh_token = Some(refresh_token.to_owned());\\n        self\\n    }\\n    pub fn set_expires_at(&mut self, expires_at: &i64) {\\n        self.expires_at = Some(*expires_at);\\n    }\\n    pub fn set_refresh_token(&mut self, refresh_token: &str) {\\n        self.refresh_token = Some(refresh_token.to_owned());\\n    }\\n}\\n\\nimpl SpotifyClientCredentials {\\n    /// build default SpotifyClientCredentials\\n    pub fn default(&self) -> SpotifyClientCredentials {\\n        dotenv().ok();\\n        let client_id = env::var(\\\"CLIENT_ID\\\").unwrap_or_default();\\n        let client_secret = env::var(\\\"CLIENT_SECRET\\\").unwrap_or_default();\\n        SpotifyClientCredentials {\\n            client_id: client_id,\\n            client_secret: client_secret,\\n            token_info: None,\\n        }\\n    }\\n\\n    pub fn client_id(mut self, client_id: &str) -> SpotifyClientCredentials {\\n        self.client_id = client_id.to_owned();\\n        self\\n    }\\n    pub fn client_secret(mut self, client_secret: &str) -> SpotifyClientCredentials {\\n        self.client_secret = client_secret.to_owned();\\n        self\\n    }\\n    pub fn token_info(mut self, token_info: TokenInfo) -> SpotifyClientCredentials {\\n        self.token_info = Some(token_info);\\n        self\\n    }\\n    pub fn build(self) -> SpotifyClientCredentials {\\n        const ERROR_MESSAGE: &str = \\\"\\n    You need to set your Spotify API credentials. You can do this by\\n    setting environment variables in `.env` file:\\n    CLIENT_ID='your-spotify-client-id'\\n    CLIENT_SECRET='your-spotify-client-secret'\\n    REDIRECT_URI='your-app-redirect-url'\\n    Get your credentials at `https://developer.spotify.com/my-applications`\\\";\\n        let mut flag = false;\\n        if self.client_secret.is_empty() {\\n            flag = true;\\n        }\\n        if self.client_id.is_empty() {\\n            flag = true;\\n        }\\n\\n        if flag {\\n            eprintln!(\\\"{}\\\", ERROR_MESSAGE);\\n        } else {\\n            debug!(\\\"client_id:{:?}, client_secret:{:?}\\\",\\n                   self.client_id,\\n                   self.client_secret);\\n        }\\n        self\\n\\n    }\\n\\n    pub fn get_access_token(&self) -> String {\\n        let mut access_token = String::new();\\n        match self.token_info {\\n            Some(ref token_info) => {\\n                if !self.is_token_expired(&token_info) {\\n                    access_token = token_info.access_token.to_owned();\\n                }\\n                access_token\\n            }\\n            None => {\\n                match self.request_access_token() {\\n                    Some(new_token_info) => new_token_info.access_token,\\n                    None => String::new(),\\n                }\\n            }\\n        }\\n    }\\n    fn is_token_expired(&self, token_info: &TokenInfo) -> bool {\\n        is_token_expired(token_info)\\n    }\\n    fn request_access_token(&self) -> Option<TokenInfo> {\\n        let mut payload = HashMap::new();\\n        payload.insert(\\\"grant_type\\\", \\\"client_credentials\\\");\\n        if let Some(mut token_info) =\\n            self.fetch_access_token(&self.client_id, &self.client_secret, &payload) {\\n            let expires_in = token_info.expires_in;\\n            token_info.set_expires_at(&datetime_to_timestamp(expires_in));\\n            Some(token_info)\\n        } else {\\n            None\\n        }\\n    }\\n    fn fetch_access_token(&self,\\n                          client_id: &str,\\n                          client_secret: &str,\\n                          payload: &HashMap<&str, &str>)\\n                          -> Option<TokenInfo> {\\n        fetch_access_token(client_id, client_secret, payload)\\n    }\\n}\\n\\nimpl SpotifyOAuth {\\n    // spotify token example:\\n    // {\\n    //    \\\"access_token\\\": \\\"NgCXRK...MzYjw\\\",\\n    //    \\\"token_type\\\": \\\"Bearer\\\",\\n    //    \\\"scope\\\": \\\"user-read-private user-read-email\\\",\\n    //    \\\"expires_in\\\": 3600,\\n    //    \\\"refresh_token\\\": \\\"NgAagA...Um_SHo\\\"\\n    // }\\n\\n    pub fn default() -> SpotifyOAuth {\\n        dotenv().ok();\\n        let client_id = env::var(\\\"CLIENT_ID\\\").unwrap_or_default();\\n        let client_secret = env::var(\\\"CLIENT_SECRET\\\").unwrap_or_default();\\n        let redirect_uri = env::var(\\\"REDIRECT_URI\\\").unwrap_or_default();\\n        SpotifyOAuth {\\n            client_id: client_id,\\n            client_secret: client_secret,\\n            redirect_uri: redirect_uri,\\n            state: generate_random_string(16),\\n            scope: String::new(),\\n            cache_path: PathBuf::from(\\\".spotify_token_cache.json\\\"),\\n            proxies: None,\\n        }\\n    }\\n    pub fn client_id(mut self, client_id: &str) -> SpotifyOAuth {\\n        self.client_id = client_id.to_owned();\\n        self\\n    }\\n    pub fn client_secret(mut self, client_secret: &str) -> SpotifyOAuth {\\n        self.client_secret = client_secret.to_owned();\\n        self\\n    }\\n    pub fn redirect_uri(mut self, redirect_uri: &str) -> SpotifyOAuth {\\n        self.redirect_uri = redirect_uri.to_owned();\\n        self\\n    }\\n    pub fn scope(mut self, scope: &str) -> SpotifyOAuth {\\n        self.scope = scope.to_owned();\\n        self\\n    }\\n    pub fn state(mut self, state: &str) -> SpotifyOAuth {\\n        self.state = state.to_owned();\\n        self\\n    }\\n    pub fn cache_path(mut self, cache_path: PathBuf) -> SpotifyOAuth {\\n        self.cache_path = cache_path;\\n        self\\n    }\\n    pub fn proxies(mut self, proxies: &str) -> SpotifyOAuth {\\n        self.proxies = Some(proxies.to_owned());\\n        self\\n    }\\n    pub fn build(self) -> SpotifyOAuth {\\n        const ERROR_MESSAGE: &str = \\\"\\n    You need to set your Spotify API credentials. You can do this by\\n    setting environment variables in `.env` file:\\n    CLIENT_ID='your-spotify-client-id'\\n    CLIENT_SECRET='your-spotify-client-secret'\\n    REDIRECT_URI='your-app-redirect-url'\\n    Get your credentials at `https://developer.spotify.com/my-applications`\\\";\\n        let mut flag = false;\\n        if self.client_secret.is_empty() {\\n            flag = true;\\n        }\\n        if self.client_id.is_empty() {\\n            flag = true;\\n        }\\n        if self.redirect_uri.is_empty() {\\n            flag = true;\\n        }\\n        if flag {\\n            eprintln!(\\\"{}\\\", ERROR_MESSAGE);\\n        } else {\\n            println!(\\\"client_id:{:?}, client_secret:{:?}, redirect_uri:{:?}\\\",\\n                     self.client_id,\\n                     self.client_secret,\\n                     self.redirect_uri);\\n        }\\n        self\\n    }\\n    pub fn get_cached_token(&mut self) -> Option<TokenInfo> {\\n        let display = self.cache_path.display();\\n        let mut file = match File::open(&self.cache_path) {\\n            Ok(file) => file,\\n            Err(why) => {\\n                println!(\\\"couldn't open {}: {:?}\\\", display, why.description());\\n                return None;\\n            }\\n        };\\n        let mut token_info_string = String::new();\\n        match file.read_to_string(&mut token_info_string) {\\n            Err(why) => panic!(\\\"couldn't read {}: {}\\\", display, why.description()),\\n            Ok(_) => {\\n                let mut token_info: TokenInfo = serde_json::from_str(&token_info_string).unwrap();\\n                if !SpotifyOAuth::is_scope_subset(&mut self.scope, &mut token_info.scope) {\\n                    return None;\\n                } else {\\n                    if self.is_token_expired(&token_info) {\\n                        if let Some(refresh_token) = token_info.refresh_token {\\n                            self.refresh_access_token(&refresh_token)\\n                        } else {\\n                            None\\n                        }\\n                    } else {\\n                        Some(token_info)\\n                    }\\n                }\\n            }\\n        }\\n    }\\n    /// gets the access_token for the app given the code\\n    pub fn get_access_token(&self, code: &str) -> Option<TokenInfo> {\\n        let mut payload: HashMap<&str, &str> = HashMap::new();\\n        payload.insert(\\\"redirect_uri\\\", &self.redirect_uri);\\n        payload.insert(\\\"code\\\", code);\\n        payload.insert(\\\"grant_type\\\", \\\"authorization_code\\\");\\n        payload.insert(\\\"scope\\\", &self.scope);\\n        payload.insert(\\\"state\\\", &self.state);\\n        if let Some(token_info) = self.fetch_access_token(&self.client_id,\\n                                                          &self.client_secret,\\n                                                          &payload) {\\n            match serde_json::to_string(&token_info) {\\n                Ok(token_info_string) => {\\n                    self.save_token_info(&token_info_string);\\n                    return Some(token_info);\\n                }\\n                Err(why) => {\\n                    panic!(\\\"couldn't convert token_info to string: {} \\\",\\n                           why.description());\\n                }\\n            }\\n        } else {\\n            None\\n        }\\n    }\\n    /// fetch access_token\\n    fn fetch_access_token(&self,\\n                          client_id: &str,\\n                          client_secret: &str,\\n                          payload: &HashMap<&str, &str>)\\n                          -> Option<TokenInfo> {\\n        fetch_access_token(client_id, client_secret, payload)\\n    }\\n    /// Parse the response code in the given response url\\n    pub fn parse_response_code(&self, url: &mut str) -> Option<String> {\\n        let tokens: Vec<&str> = url.split(\\\"?code=\\\").collect();\\n        let strings: Vec<&str> = tokens[1].split(\\\"&\\\").collect();\\n        let code = strings[0];\\n        Some(code.to_owned())\\n    }\\n    /// Gets the URL to use to authorize this app\\n    pub fn get_authorize_url(&self, state: Option<&str>, show_dialog: Option<bool>) -> String {\\n        let mut payload: HashMap<&str, &str> = HashMap::new();\\n        payload.insert(\\\"client_id\\\", &self.client_id);\\n        payload.insert(\\\"response_type\\\", \\\"code\\\");\\n        payload.insert(\\\"redirect_uri\\\", &self.redirect_uri);\\n        if let Some(state) = state {\\n            payload.insert(\\\"state\\\", state);\\n        }\\n        if let Some(show_dialog) = show_dialog {\\n            payload.insert(\\\"show_diaload\\\", \\\"true\\\");\\n        }\\n\\n        let query_str = convert_map_to_string(&payload);\\n        let mut authorize_url = String::from(\\\"https://accounts.spotify.com/authorize?\\\");\\n        authorize_url\\n            .push_str(&utf8_percent_encode(&query_str, PATH_SEGMENT_ENCODE_SET).to_string());\\n        println!(\\\"{:?}\\\", &authorize_url);\\n        authorize_url\\n    }\\n    /// after refresh access_token, the response may be empty\\n    /// when refresh_token again\\n    pub fn refresh_access_token(&self, refresh_token: &str) -> Option<TokenInfo> {\\n        let mut payload = HashMap::new();\\n        payload.insert(\\\"refresh_token\\\", refresh_token);\\n        payload.insert(\\\"grant_type\\\", \\\"refresh_token\\\");\\n        if let Some(token_info) = self.fetch_access_token(&self.client_id,\\n                                                          &self.client_secret,\\n                                                          &payload) {\\n            match serde_json::to_string(&token_info) {\\n                Ok(token_info_string) => {\\n                    self.save_token_info(&token_info_string);\\n                    return Some(token_info);\\n                }\\n                Err(why) => {\\n                    panic!(\\\"couldn't convert token_info to string: {} \\\",\\n                           why.description());\\n                }\\n            }\\n        } else {\\n            None\\n        }\\n    }\\n    fn save_token_info(&self, token_info: &str) {\\n        save_token_info(token_info, self.cache_path.as_path())\\n    }\\n    fn is_scope_subset(needle_scope: &mut str, haystack_scope: &mut str) -> bool {\\n        let needle_vec: Vec<&str> = needle_scope.split_whitespace().collect();\\n        let haystack_vec: Vec<&str> = haystack_scope.split_whitespace().collect();\\n        let needle_set: HashSet<&str> = HashSet::from_iter(needle_vec);\\n        let haystack_set: HashSet<&str> = HashSet::from_iter(haystack_vec);\\n        // needle_set - haystack_set\\n        needle_set.is_subset(&haystack_set)\\n    }\\n    fn is_token_expired(&self, token_info: &TokenInfo) -> bool {\\n        is_token_expired(token_info)\\n    }\\n}\\n\\nfn is_token_expired(token_info: &TokenInfo) -> bool {\\n    let now: DateTime<Utc> = Utc::now();\\n    // 10s as buffer time\\n    match token_info.expires_at {\\n        Some(expires_at) => now.timestamp() > expires_at - 10,\\n        None => true,\\n    }\\n}\\nfn save_token_info(token_info: &str, path: &Path) {\\n    let mut file = OpenOptions::new()\\n        .write(true)\\n        .create(true)\\n        .open(path)\\n        .expect(\\\"error\\\");\\n    file.write_all(token_info.as_bytes())\\n        .expect(\\\"error when write file\\\");\\n}\\n\\nfn fetch_access_token(_client_id: &str,\\n                      _client_secret: &str,\\n                      payload: &HashMap<&str, &str>)\\n                      -> Option<TokenInfo> {\\n    let client = Client::new();\\n    let client_id = _client_id.to_owned();\\n    let client_secret = _client_secret.to_owned();\\n    let credentials = Basic {\\n        username: client_id,\\n        password: Some(client_secret),\\n    };\\n    let url = \\\"https://accounts.spotify.com/api/token\\\";\\n    let mut response = client\\n        .post(url)\\n        .header(Authorization(credentials))\\n        .form(&payload)\\n        .send()\\n        .expect(\\\"send request failed\\\");\\n    let mut buf = String::new();\\n    response\\n        .read_to_string(&mut buf)\\n        .expect(\\\"failed to read response\\\");\\n    if response.status().is_success() {\\n        println!(\\\"{:?}\\\", buf);\\n        let mut token_info: TokenInfo = serde_json::from_str(&buf).unwrap();\\n        // .expect(\\\"parsing response content to tokenInfo error\\\");\\n        let expires_in = token_info.expires_in;\\n        token_info.set_expires_at(&datetime_to_timestamp(expires_in));\\n        if token_info.refresh_token.is_none() {\\n            match payload.get(\\\"refresh_token\\\") {\\n                Some(payload_refresh_token) => {\\n                    token_info.set_refresh_token(&payload_refresh_token);\\n                    return Some(token_info);\\n                }\\n                None => {\\n                    println!(\\\"could not find refresh_token\\\");\\n                }\\n            }\\n        }\\n        Some(token_info)\\n    } else {\\n        println!(\\\"fetch access token request failed, payload:{:?}\\\", &payload);\\n        println!(\\\"{:?}\\\", response);\\n        None\\n    }\\n}\\n\\n#[cfg(test)]\\nmod tests {\\n    use super::*;\\n    use std::path::PathBuf;\\n    use serde_json;\\n    #[test]\\n    fn test_is_scope_subset() {\\n        let mut needle_scope = String::from(\\\"1 2 3\\\");\\n        let mut haystack_scope = String::from(\\\"1 2 3 4\\\");\\n        let mut broken_scope = String::from(\\\"5 2 4\\\");\\n        assert!(SpotifyOAuth::is_scope_subset(&mut needle_scope, &mut haystack_scope));\\n        assert!(!SpotifyOAuth::is_scope_subset(&mut broken_scope, &mut haystack_scope));\\n    }\\n    #[test]\\n    fn test_save_token_info() {\\n        let spotify_oauth = SpotifyOAuth::default()\\n            .state(&generate_random_string(16))\\n            .scope(\\\"user-read-mail\\\")\\n            .cache_path(PathBuf::from(\\\".test_token\\\"))\\n            .build();\\n        let token_info = TokenInfo::new()\\n            .access_token(\\\"test-access_token\\\")\\n            .token_type(\\\"code\\\")\\n            .expires_in(3600)\\n            .expires_at(1515841743)\\n            .scope(\\\"user-read-email\\\")\\n            .refresh_token(\\\"fghjklrftyhujkuiovbnm\\\");\\n        match serde_json::to_string(&token_info) {\\n            Ok(token_info_string) => {\\n                spotify_oauth.save_token_info(&token_info_string);\\n                let display = spotify_oauth.cache_path.display();\\n                let mut file = match File::open(&spotify_oauth.cache_path) {\\n                    Err(why) => panic!(\\\"couldn't open {}: {}\\\", display, why.description()),\\n                    Ok(file) => file,\\n                };\\n                let mut token_info_string_from_file = String::new();\\n                match file.read_to_string(&mut token_info_string_from_file) {\\n                    Err(why) => panic!(\\\"couldn't read {}: {}\\\", display, why.description()),\\n                    Ok(_) => {\\n                        assert_eq!(token_info_string, token_info_string_from_file);\\n                    }\\n                }\\n            }\\n            Err(why) => {\\n                panic!(\\\"couldn't convert token_info to string: {} \\\",\\n                       why.description())\\n            }\\n        }\\n    }\\n\\n    #[test]\\n    fn test_parse_response_code() {\\n        let mut url = String::from(\\\"http://localhost:8888/callback?code=AQD0yXvFEOvw&state=sN#_=_\\\");\\n        let spotify_oauth = SpotifyOAuth::default()\\n            .state(&generate_random_string(16))\\n            .scope(\\\"user-read-mail\\\")\\n            .cache_path(PathBuf::from(\\\".test_token\\\"))\\n            .build();\\n        match spotify_oauth.parse_response_code(&mut url) {\\n            Some(code) => assert_eq!(code, \\\"AQD0yXvFEOvw\\\"),\\n            None => panic!(\\\"failed\\\"),\\n        }\\n    }\\n}\\n\"}}}" #<process lsp-rust>)
  lsp--text-document-did-open()
  (let* ((root (funcall (progn nil (or (progn nil (and ... ... ... t)) (signal (quote wrong-type-argument) (list ... client))) (aref client 7)))) (workspace (gethash root lsp--workspaces)) new-conn response init-params parser proc cmd-proc) (if workspace (setq lsp--cur-workspace workspace) (progn (setq parser (progn "Constructor for objects of type `lsp--parser'." nil (vector (quote cl-struct-lsp--parser) nil nil (quote nil) nil nil nil 0 nil nil nil nil))) (setq lsp--cur-workspace (make-lsp--workspace :parser parser :file-versions (make-hash-table :test (quote equal)) :root root :client client)) (progn nil (or (and (memq (aref parser 0) cl-struct-lsp--parser-tags)) (signal (quote wrong-type-argument) (list (quote lsp--parser) parser))) (let* ((v parser)) (aset v 11 lsp--cur-workspace))) (setq new-conn (funcall (progn nil (or (progn nil ...) (signal ... ...)) (aref client 5)) (lsp--parser-make-filter parser (progn nil (or ... ...) (aref client 8))) (lsp--make-sentinel (current-buffer) (progn nil (or ... ...) (aref client 6))))) (setq cmd-proc (if (consp new-conn) (car new-conn) new-conn)) (setq proc (if (consp new-conn) (cdr new-conn) new-conn)) (progn nil (or (progn nil (and (vectorp lsp--cur-workspace) (>= ... 13) (memq ... cl-struct-lsp--workspace-tags) t)) (signal (quote wrong-type-argument) (list (quote lsp--workspace) lsp--cur-workspace))) (let* ((v lsp--cur-workspace)) (aset v 8 proc))) (progn nil (or (progn nil (and (vectorp lsp--cur-workspace) (>= ... 13) (memq ... cl-struct-lsp--workspace-tags) t)) (signal (quote wrong-type-argument) (list (quote lsp--workspace) lsp--cur-workspace))) (let* ((v lsp--cur-workspace)) (aset v 9 cmd-proc)))) (puthash root lsp--cur-workspace lsp--workspaces) (run-hooks (quote lsp-before-initialize-hook)) (setq init-params (list (quote :processId) (emacs-pid) (quote :rootPath) root (quote :rootUri) (lsp--path-to-uri root) (quote :capabilities) (lsp--client-capabilities) (quote :initializationOptions) (if (functionp extra-init-params) (funcall extra-init-params lsp--cur-workspace) extra-init-params))) (setq response (lsp--send-request (plist-put (progn (progn (or ... ...) nil) (list :jsonrpc "2.0" :method "initialize" :params init-params)) :id (progn nil (or (progn nil ...) (signal ... ...)) (let* (...) (aset v 13 ...)))))) (if response nil (signal (quote lsp-empty-response-error) (list "initialize"))) (progn nil (or (progn nil (and (vectorp lsp--cur-workspace) (>= (length lsp--cur-workspace) 13) (memq (aref lsp--cur-workspace 0) cl-struct-lsp--workspace-tags) t)) (signal (quote wrong-type-argument) (list (quote lsp--workspace) lsp--cur-workspace))) (let* ((v lsp--cur-workspace)) (aset v 3 (gethash "capabilities" response)))) (lsp--send-no-wait (lsp--make-message (progn (progn (or (stringp "initialized") (signal ... ...)) nil) (list :jsonrpc "2.0" :method "initialized" :params nil))) (progn nil (or (progn nil (and (vectorp lsp--cur-workspace) (>= ... 13) (memq ... cl-struct-lsp--workspace-tags) t)) (signal (quote wrong-type-argument) (list (quote lsp--workspace) lsp--cur-workspace))) (aref lsp--cur-workspace 8))) (run-hooks (quote lsp-after-initialize-hook))) (lsp--text-document-did-open))
  lsp--start([cl-struct-lsp--client #[(_) "\300\207" ["rust"] 1 "rust"] nil nil nil #[514 "\302\203	
```

**Comment by samrayleung** [comment]
Wow, it works. Thanks so much for your help :)
