### ISSUE TITLE
Incorrect Completion

### ISSUE THREAD

**Issue by nickenchev** [emacs-lsp/lsp-mode#339]
I recently updated cquery, which I use via emacs-lsp and company-lsp and have started noticing the following issue. The cquery author has asked me to file the issue with emacs-lsp, so here are the details, as well as the original issue URL for reference:
https://github.com/cquery-project/cquery/issues/606#issuecomment-379980413

When I start typing for a completion, emacs makes the suggestion, I hit enter too select it, but then the actual suggestion isn't inserted, but rather the last character (or 2) that I entered in order to get the suggestion. See the images below for an example using std::vector.

<img width="331" alt="screen shot 2018-04-09 at 11 55 56 am" src="https://user-images.githubusercontent.com/8262271/38508690-e54e30ec-3bed-11e8-8704-126f31712948.png">

Now I start typing "std::ve" to get "vector" as a completion.
<img width="333" alt="screen shot 2018-04-09 at 11 56 08 am" src="https://user-images.githubusercontent.com/8262271/38508702-e8895c50-3bed-11e8-9669-1ba08909718a.png">

I hit enter and get the following result:
<img width="337" alt="screen shot 2018-04-09 at 11 56 17 am" src="https://user-images.githubusercontent.com/8262271/38508723-f37a1302-3bed-11e8-9c03-4ab249c84975.png">

**Comment by yyoncho** [comment]
Fixed by https://github.com/tigersoldier/company-lsp/pull/36

**Comment by nickenchev** [comment]
Trying the completion via M-x "complete-symbol (C-M-i)" and everything is working well. When I turn company back on, the error still persists. Has company-lsp (MELPA) actually been updated?

The commit is from 2018-05-04: https://github.com/tigersoldier/company-lsp/commit/141d58f8330958d9fb755992f5ba9b586ac98a66

The MELPA badge says 20180429, the package installed is "company-lsp-20180503.2319/", which is still a day behind. In any case, I'm still seeing the same problem when using company + cquery completions.

Start completion
<img width="551" alt="screen shot 2018-05-13 at 11 06 16 am" src="https://user-images.githubusercontent.com/8262271/39968602-b956d1cc-569d-11e8-87a2-9586df53ae71.png">
Hit enter to select:
<img width="252" alt="screen shot 2018-05-13 at 11 06 30 am" src="https://user-images.githubusercontent.com/8262271/39968603-bd7442b2-569d-11e8-8b4b-12d38fc925e5.png">

**Comment by yyoncho** [comment]
I believe you are hitting https://github.com/tigersoldier/company-lsp/issues/39 . You could workaround the issue by setting `company-lsp-cache-candidates` to `nil`. There is pending pull request https://github.com/tigersoldier/company-lsp/pull/41 .

**Comment by nickenchev** [comment]
(setq company-lsp-cache-candidates nil) fixed the issue for me. I'll keep an eye on the pull request and remove the workaround when its available mainline. Thanks for the quick response.

**Comment by yyoncho** [comment]
The fix is in, can you try with latest company lsp?

**Comment by nickenchev** [comment]
Looks good! Took out the fix you workaround, updated all packages, updated cquery executable.

Thanks!
