### ISSUE TITLE
Possible memory leak in the recent versions of lsp-mode

### ISSUE THREAD

**Issue by grendello** [emacs-lsp/lsp-mode#3821]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [x] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

To be honest, I'm not entirely sure the problem lies in `lsp-mode`, but the process of elimination appears to suggest that it is.

As of the past 7-10 days, I've started to observe that Emacs (`GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.16.0) of 2022-11-17, modified by Debian`) started to leak memory like a sieve
when `lsp-mode` with any server (observed with `OmniSharp`, `ccls`, `clangd` at least).  The leak is slower with smaller projects, obviously, but when opening a large repo like [Xamarin.Android](https://github.com/xamarin/xamarin-android), after a couple of hours (8 source files open, the biggest is around 20k) Emacs uses 7-10 GB of RAM (I can make it OOM after using nearly 50GB of RAM with one specific configuration, thanks to `OmniSharp` throwing hundreds of exceptions per second, irrelevant to this issue):

![emacs-lsp-mem-usage](https://user-images.githubusercontent.com/184788/203647438-c463fb9d-e86c-438c-8e46-082cff38ce2b.png)

The memory usage of the `OmniSharp` instances above remained stable, while Emacs resident set keeps growing - any edit action causes some memory usage growth, but the biggest leap is when a new file is loaded or a buffer using `lsp-mode` is closed.  It appears that any request sent to the backend allocates memory that is never freed.  The only way to reclaim it is to restart Emacs :(

Initially I suspected the leak might be in the native tree-sitter shared libraries, but after disabling any tree-sitter usage the problem persists. I also don't see the leak when `lsp-mode` isn't used, thus this issue :)

The `*lsp-log*` doesn't contain anything suspicious, except for the usual stuff.

### Steps to reproduce

Just use `lsp-mode` in the usual way, bigger projects show the problem faster than the smaller ones.

### Expected behavior

Don't leak memory

### Which Language Server did you use?

`OmniSharp`, `ccls`, `clangd`, `cmakels`

### OS

Linux

### Anything else?

Also tried with a build of Emacs from the `emacs-28` branch (`GNU Emacs 28.2.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.16.0) of 2022-11-23`) to see if it's perhaps some of Debian modifications, but the problem exists there as well.

**Comment by grendello** [comment]
Just tried to reproduce the problem in a clean environment and memory usage is stable there, edit actions don't cause any leaks.

**Comment by yangyingchao** [comment]
I have similar issue here with emacs-29 (compiled from git), but not 100% reproducible. I use lsp-clangd, and sometimes when `xref-find-reference` is called, memory usage goes high very quickly.

When this happens, I send `SIGSTOP` to emacs, attach it with gdb, and find out that in most cases, process is doing something related to timestamp & float numbers (issued by `lsp-request`).

There is a PR #3821 which is related timestamps, I'll check if it fixes my issue here.https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Comment by yangyingchao** [comment]
I had similar issue, and it seems get fixed by PR #3823

**Comment by grendello** [comment]
Is this in melpa already? I'm using the latest version from there and I still see the leak, although it is indeed slower. I see it with both Emacs 28.2 as well as the tip of the 29 branch.

**Comment by yyoncho** [comment]
Fixed with https://github.com/emacs-lsp/lsp-mode/commit/03fc8b87516223ebd2b68a2af20ec8775eeb0547

**Comment by grendello** [comment]
@yyoncho I'm afraid the original problem is back :( After https://github.com/emacs-lsp/lsp-mode/commit/03fc8b87516223ebd2b68a2af20ec8775eeb0547 things got better, but I'm seeing the problem again with OmniSharp (latest tip of their master branch). Having a handful of small files open:

![image](https://user-images.githubusercontent.com/184788/213488834-a1e7c771-6d89-4bc7-ba05-b8ba245d2e28.png)

I'm seeing RAM usage of 4.1GB after around 30 minutes of editing:

![image](https://user-images.githubusercontent.com/184788/213489476-3fcc3263-7579-4c22-bb79-2892bc410722.png)

It seems that the very first edit to any file allocates around 100MB of RAM.

In the `*lsp-log*` buffer I see a few exceptions thrown by OmniSharp on each file open, which may or may not be related to the issue:

```
OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker: Failed to handle request textDocument/didOpen - System.ArgumentException: ToolRunner.cs is still open.
```

As well as a few of these (which might be a bug in OmniSharp, but perhaps they trigger the leaks in `lsp-mode` somehow, sending back an invalid response for instance, which then isn't handled properly?):

```
OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker: Failed to handle request textDocument/completion 803 - System.InvalidOperationException: Unexpected null - line 226
   at Roslyn.Utilities.Contract.Fail(String message, Int32 lineNumber)
   at Microsoft.CodeAnalysis.Snippets.AbstractSnippetProvider.AnnotateNodesToReformatAsync(Document document, SyntaxAnnotation findSnippetAnnotation, SyntaxAnnotation cursorAnnotation, Int32 position, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Snippets.AbstractSnippetProvider.AddFormatAnnotationAsync(Document document, Int32 position, CancellationToken cancellationToken)
```

as well as plenty of messages similar to

```
Cancelling textDocument/codeAction(670) in hook after-change-functions
```

I'm using current emacs in Debian/unstable (`GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.36, cairo version 1.16.0) of 2023-01-18, modified by Debian`) and the `lsp-mode` `20230117.1411` from MELPA.

Please let me know if I (and how) I could provide you with more information
