### ISSUE TITLE
rust: no details in completion popup

### ISSUE THREAD

**Issue by ensc** [emacs-lsp/lsp-mode#4591]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

With recent "rust-analyzer" versions, completion does not contain details anymore.  E.g. with rust-analyzer 1.83.0- nightly (eb4e234 2024-10-09) and later I get

![image](https://github.com/user-attachments/assets/97fb68b0-1a0c-4ebd-b96a-fdfdae6ea2a6)

Previous versions (e.g. rust-analyzer 1.83.0-nightly (55a22d2 2024-10-06)) showed

![image](https://github.com/user-attachments/assets/c3d58fef-8dfa-44f0-99d3-8a7f1f74fd3c)

Looking in the io log shows that "detail" and "documentation" attributes are missing with recent rust-analyzer.

See https://github.com/rust-lang/rust-analyzer/issues/18351 too.

### Steps to reproduce

Try to complete in rust sources.

### Expected behavior

full function signature should be shown in the popup

### Which Language Server did you use?

rust-analyzer

### OS

Linux

**Comment by jcs090218** [comment]
Thanks for reporting this issue.

Is this the expected behavior from the upstream (language server)? 🤔

**Comment by ensc** [comment]
rust-analyzer developers say in https://github.com/rust-lang/rust-analyzer/issues/18351#issuecomment-2428295678

> That sounds like the client is telling r-a it supports lazily resolving those fields, so the client needs to also send a corresponding resolve request

This was added by https://github.com/rust-lang/rust-analyzer/pull/18167

Recommendation sounds very expensive to me (but I do not have any idea about the LSP protocol) and disabling lazy-resolve support sounds better.

**Comment by kiennq** [comment]
Can you try to move to the next item in the completion list to see if the function detail will be displayed for the previously selected item?
`lsp-mode` does support lazy resolving for better perf due to less data passing and json processing. But it's triggered when item's document is requested, i.e, when the item is focused, `company-mode` will request the document for the focused item.
Probably that can be improved to show the detail for all displayed item instead

**Comment by ensc** [comment]
> Can you try to move to the next item in the completion list to see if the function detail will be displayed for the previously selected item?

does not have an effect; details are not shown

![image](https://github.com/user-attachments/assets/98023202-db73-48ac-8743-f7c7b9ae4b67)

**Comment by kiennq** [comment]
> For me, this sounds very expensive. E.g. instead of parsing a "detail" (and perhaps "documentation") attribute in hundreds/thousands of completion candidates

The point is server can opt-in into this if it makes sense for them. You can see, fetching documentation and details of hundreds/thousands of candidates can be very expensive as it hit disk to get the documentation. Moreover, that fetching happens on every single keystroke that most likely the user doesn't care about. Also, that make processing every keystroke become slower.

When lazy-resolving is supported, that means there's no waste to retrieve more information (and potentially disk reading) when the user is typing. Now, after the user has finish typing and starts looking at the candidates, we can start fetching candidates' detail when the user is interacting with __normally__ a smaller number of candidates instead of all candidates. And they should be quicker than fetching the whole data at the beginning so the user would feel LSP run faster as well.

**Comment by ensc** [comment]
> The point is server can opt-in into this if it makes sense for them

Sounds like a design flaw of the LSP protocol... Clients should be able to set this per request.  E.g. minimal set of information for the per-keystroke action and detailed set for the dropdown list with completions.


> Moreover, that fetching happens on every single keystroke that most likely the user doesn't care about.

I do not see this here: `textDocument/completion` request happens some time after I stop typing.  Perhaps because I have `(lsp-idle-delay 1)`


> we can start fetching candidates' detail when the user is interacting with normally a smaller number of candidates instead of all candidates

For my use case I do not see a big reduction of candidates.  E.g. often when I look in the completion dropdown list, I have only a raw idea about the naming of the method and have to browse large parts of the list to find the correct one.

I am ok with fetching "documentation" lazily (large amount of text which should be displayed only for a selected item); but "detail" is an essential information which should be made available in the dropdown list immediately.

**Comment by kiennq** [comment]
> For my use case I do not see a big reduction of candidates. E.g. often when I look in the completion dropdown list, I have only a raw idea about the method (naming, return type) and have to browse large parts of the list to find the correct one.

Even in that case, you will have more time to look at each candidate than having to fetch everything at first.
LSP is designed for a general editor and not only Emacs with idle delay to fetch the candidates. The editor client (Emacs) in this case can opt-in into saying that they don't support lazy resolving as well. However, even with idle delay to fetch the candidates, processing more data makes Emacs slower and shows the candidates slower as well. Opt-in into lazy resolving allows Emacs to just process a piece of smaller information and display it faster, which can be significant if the language server is in remote (TRAMP) instead of local machine.
I think what we can improve here is to lazy resolve all of displayed candidates (9) asynchronously so that it doesn't affect the UX.

Btw, I've tried with the nightly build of Windows and it seems that the detail is still fetched and not lazy-resolved.

**Comment by ensc** [comment]
> which can be significant if the language server is in remote (TRAMP) instead of local machine.

this seems to make lazy-resolving yet more slower...  Hundreds of resolve requests to fill the completion dialog might be no network issue when sent locally.  But over TRAMP?

What would be the effects when "detail" is removed from "resolveSupport"?  Would this attribute be missing from the resolve answer?  Or would it just reenable it in the `textDocument/completion` response?  


> However, even with idle delay to fetch the candidates, processing more data makes Emacs slower

At least with rust, the "detail" property is so small compared with the rest of the response, that the difference is probably not noticable.


> Btw, I've tried with the nightly build of Windows and it seems that the detail is still fetched and not lazy-resolved.

strange;  here it is

```
$ rust-analyzer --version
rust-analyzer 1.84.0-nightly (1e4f10b 2024-10-29)
```

and I tested it with `M-x lsp-start-plain`.

**Comment by traviscross** [comment]
It was thought that PR #4610 might solve this, but in testing with rust-analyzer at commit https://github.com/rust-lang/rust-analyzer/commit/fc98e0657abf3ce07eed513e38274c89bbb2f8ad along with lsp-mode `20241113.743` (which contains PR #4610), the problem still reproduces.

**Comment by wyuenho** [comment]
I don't believe #4610 is a desirable fix for 2 reasons: 

1. This issue is probably a bug in rust-analyzer in that they've misinterpreted the LSP spec, I've explained the [rationale here](https://github.com/emacs-lsp/lsp-mode/pull/4609#issuecomment-2525118614).

2. #4610 treats the completion items from `textDocument/completion` and `completionItem/resolve` the same, which causes UI problems for pretty much every other language servers and completion UIs, including the server VS Code is originally designed for - ts-ls.

**Comment by wyuenho** [comment]
Just finished testing on rust-analyzer 1.83.0, there's clearly detail and documentation returned from `textDocument/completion`.

```json 
  ...
  
        "completion": {
        "completionItem": {
          ...
          "resolveSupport": {
            "properties": [
              "documentation",
              "detail",
              "additionalTextEdits",
              "command",
              "insertTextFormat",
              "insertTextMode"
            ]
          },
...

 "serverInfo": {
    "name": "rust-analyzer",
    "version": "1.83.0 (90b35a62 2024-11-26)"
  }
  
...
[Trace - 04:11:20 PM] Received response 'textDocument/completion - (184)' in 114ms.
Result: {
  "isIncomplete": true,
  "items": [
    {
      "additionalTextEdits": [],
      "command": {
        "command": "rust-analyzer.triggerParameterHints",
        "title": "triggerParameterHints"
      },
      "data": {
        "imports": [
          {
            "full_import_path": "std::fs::read_dir",
            "imported_name": "read_dir"
          }
        ],
        "position": {
          "position": {
            "character": 7,
            "line": 15
          },
          "textDocument": {
            "uri": "file:///snipped/src/main.rs"
          }
        },
        "version": 8
      },
      "deprecated": null,
      "detail": "fn(P) -> Result<ReadDir, Error>",
      "documentation": {
        "kind": "markdown",
        "value": "Returns an iterator over the entries within a directory.\n\nThe iterator will yield instances of <code>[io::Result]<[DirEntry]></code>.\nNew errors may be encountered after an iterator is initially constructed.\nEntries for the current and parent directories (typically `.` and `..`) are\nskipped.\n\n# Platform-specific behavior\n\nThis function currently corresponds to the `opendir` function on Unix\nand the `FindFirstFile` function on Windows. Advancing the iterator\ncurrently corresponds to `readdir` on Unix and `FindNextFile` on Windows.\nNote that, this [may change in the future][changes].\n\n[changes]: io#platform-specific-behavior\n\nThe order in which this iterator returns entries is platform and filesystem\ndependent.\n\n# Errors\n\nThis function will return an error in the following situations, but is not\nlimited to just these cases:\n\n* The provided `path` doesn't exist.\n* The process lacks permissions to view the contents.\n* The `path` points at a non-directory file.\n\n# Examples\n\n```rust\nuse std::io;\nuse std::fs::{self, DirEntry};\nuse std::path::Path;\n\n// one possible implementation of walking a directory only visiting files\nfn visit_dirs(dir: &Path, cb: &dyn Fn(&DirEntry)) -> io::Result<()> {\n    if dir.is_dir() {\n        for entry in fs::read_dir(dir)? {\n            let entry = entry?;\n            let path = entry.path();\n            if path.is_dir() {\n                visit_dirs(&path, cb)?;\n            } else {\n                cb(&entry);\n            }\n        }\n    }\n    Ok(())\n}\n```\n\n```rust\nuse std::{fs, io};\n\nfn main() -> io::Result<()> {\n    let mut entries = fs::read_dir(\".\")?\n        .map(|res| res.map(|e| e.path()))\n        .collect::<Result<Vec<_>, io::Error>>()?;\n\n    // The order in which `read_dir` returns entries is not guaranteed. If reproducible\n    // ordering is required the entries should be explicitly sorted.\n\n    entries.sort();\n\n    // The entries have now been sorted by their path.\n\n    Ok(())\n}\n```"
      },

```

**Comment by wyuenho** [comment]
BTW I can't reproduce this issue on 1.83.0 anymore. @ensc Is this solved by https://github.com/rust-lang/rust-analyzer/pull/18388  as stated [here](https://github.com/rust-lang/rust-analyzer/issues/18351#issuecomment-2433368697) ?

**Comment by traviscross** [comment]
Probably this revert...

- https://github.com/rust-lang/rust/pull/133476

...would have made this unreproducible in r-a 1.83.0.

**Comment by ensc** [comment]
> @ensc Is this solved by [rust-lang/rust-analyzer#18388](https://github.com/rust-lang/rust-analyzer/pull/18388) as stated [here](https://github.com/rust-lang/rust-analyzer/issues/18351#issuecomment-2433368697) ?

With lsp-mode 20241202.334 + rust-analyzer 1.85.0-nightly (9c707a8 2024-12-07) I still see the effect from the initial report (no details in popup).

Details appear after selecting another item in the list (which was added by #4610);  while this is a huge improvement, I am still not used at it and miss the old behavior where details are visible immediately.

**Comment by wyuenho** [comment]
@SomeoneToIgnore after out nice little discussion last night, is there a plan to roll back all remnants of https://github.com/rust-lang/rust/pull/133476 ?

**Comment by wyuenho** [comment]
@ensc BTW, are you using company or corfu?

**Comment by dgutov** [comment]
> The issue with company eagerly resolving the entire completion list is a little problematic, perhaps it should follow what 4610 and corfu-pixel-perfect has done, i.e. follow the VS Code model

A more concrete proposal might help.

Offhand, I can say that company doesn't resolve the entire completion list - only the entries currently visible in the popup, as well as some annotations (for entries that are string-equal to each other). And the details of that really depend on the implementation in lsp-mode. But if a handful of "resolve" operations can be expensive, then I suppose that could still be suboptimal.

**Comment by wyuenho** [comment]
Sorry I mean #4625 , I've tagged you over there, let's move our convo there.

**Comment by ensc** [comment]
> @ensc BTW, are you using company or corfu?

company

**Comment by wyuenho** [comment]
Comfirmed this is still happening with rust-analyzer nightly. This is likely a bug in R-A, as [suggested here](https://github.com/emacs-lsp/lsp-mode/pull/4609#issuecomment-2525268009). There's no reason R-A should skip the detail in the response of `textDocument/completion`. Let's file an issue over there instead.

**Comment by wyuenho** [comment]
This should have been fixed now

**Comment by traviscross** [comment]
In retesting with the latest nightly rust-analyzer and with the latest released lsp-mode, this is now working correctly.
