### ISSUE TITLE
3 failing tests while building on Debian

### ISSUE THREAD

**Issue by thkoch2001** [emacs-lsp/lsp-mode#467]
I'm trying to build a Debian package of lsp-mode. The tests get executed during the build and these fail:

```
Test lsp-file-watch--notifications backtrace:                                                                                                                                                  
  (if (unwind-protect (setq value-52 (apply fn-50 args-51)) (setq form                                                                                                                         
  (let (form-description-54) (if (unwind-protect (setq value-52 (apply                                                                                                                         
  (let ((value-52 (quote ert-form-evaluation-aborted-53))) (let (form-                                                                                                                         
  (let ((fn-50 (function equal)) (args-51 (list events expected-events                                                                                                                         
  (let* ((temp-directory (file-name-as-directory (concat temporary-fil                                                                                                                         
  (closure (t) nil (let* ((temp-directory (file-name-as-directory (con                                                                                                                         
  ert--run-test-internal([cl-struct-ert--test-execution-info [cl-struc                                                                                                                         
  ert-run-test([cl-struct-ert-test lsp-file-watch--notifications nil (                                                                                                                         
  ert-run-or-rerun-test([cl-struct-ert--stats t [[cl-struct-ert-test l                                                                                                                         
  ert-run-tests(t #[385 "\306\307\"\203G\211\211G\310U\203\211@\20                                                                                                                             
  ert-run-tests-batch(nil)                                                                                                                                                                     
  ert-run-tests-batch-and-exit()                                                                                                                                                               
  eval((ert-run-tests-batch-and-exit))                                                                                                                                                         
  command-line-1(("-l" "package" "--eval" "(add-to-list 'package-direc                                                                                                                         
  command-line()                                                                                                                                                                               
  normal-top-level()                                                                                                                                                                           
Test lsp-file-watch--notifications condition:                                                                                                                                                  
    (ert-test-failed                                                                                                                                                                           
     ((should                                                                                                                                                                                  
       (equal events expected-events))                                                                                                                                                         
      :form                                                                                                                                                                                    
      (equal nil                                                                                                                                                                               
             ((changed "/tmp/common-test-dir/file.ext")                                                                                                                                        
              (created "/tmp/common-test-dir/file.ext")))                                                                                                                                      
      :value nil :explanation                                                                                                                                                                  
      (different-types nil                                                                                                                                                                     
                       ((changed "/tmp/common-test-dir/file.ext")                                                                                                                              
                        (created "/tmp/common-test-dir/file.ext")))))                                                                                                                          
   FAILED  14/16  lsp-file-watch--notifications
```

```
Test lsp-file-watch--relative-path backtrace:                                                                                                                                                  
  (if (unwind-protect (setq value-97 (apply fn-95 args-96)) (setq form                                                                                                                         
  (let (form-description-99) (if (unwind-protect (setq value-97 (apply                                                                                                                         
  (let ((value-97 (quote ert-form-evaluation-aborted-98))) (let (form-                                                                                                                         
  (let ((fn-95 (function equal)) (args-96 (list expected-events events                                                                                                                         
  (let* ((temp-directory (file-name-as-directory (concat temporary-fil                                                                                                                         
  (closure (t) nil (let* ((temp-directory (file-name-as-directory (con                                                                                                                         
  ert--run-test-internal([cl-struct-ert--test-execution-info [cl-struc                                                                                                                         
  ert-run-test([cl-struct-ert-test lsp-file-watch--relative-path nil (                                                                                                                         
  ert-run-or-rerun-test([cl-struct-ert--stats t [[cl-struct-ert-test l                                                                                                                         
  ert-run-tests(t #[385 "\306\307\"\203G\211\211G\310U\203\211@\20                                                                                                                             
  ert-run-tests-batch(nil)                                                                                                                                                                     
  ert-run-tests-batch-and-exit()                                                                                                                                                               
  eval((ert-run-tests-batch-and-exit))                                                                                                                                                         
  command-line-1(("-l" "package" "--eval" "(add-to-list 'package-direc                                                                                                                         
  command-line()                                                                                                                                                                               
  normal-top-level()                                                                                                                                                                           
Test lsp-file-watch--relative-path condition:
    (ert-test-failed
     ((should
       (equal expected-events events))
      :form
      (equal
       ((changed "/tmp/common-test-dir/file.ext")
        (created "/tmp/common-test-dir/file.ext"))
       nil)
      :value nil :explanation
      (different-types
       ((changed "/tmp/common-test-dir/file.ext")
        (created "/tmp/common-test-dir/file.ext"))
       nil)))
   FAILED  15/16  lsp-file-watch--relative-path
```

```
Test lsp-file-watch--relative-path-glob-patterns backtrace:
  (if (unwind-protect (setq value-102 (apply fn-100 args-101)) (setq f
  (let (form-description-104) (if (unwind-protect (setq value-102 (app
  (let ((value-102 (quote ert-form-evaluation-aborted-103))) (let (for
  (let ((fn-100 (function equal)) (args-101 (list expected-events even
  (let* ((temp-directory (file-name-as-directory (concat temporary-fil
  (closure (t) nil (let* ((temp-directory (file-name-as-directory (con
  ert--run-test-internal([cl-struct-ert--test-execution-info [cl-struc
  ert-run-test([cl-struct-ert-test lsp-file-watch--relative-path-glob-
  ert-run-or-rerun-test([cl-struct-ert--stats t [[cl-struct-ert-test l
  ert-run-tests(t #[385 "\306\307\"\203G\211\211G\310U\203\211@\20
  ert-run-tests-batch(nil)
  ert-run-tests-batch-and-exit()
  eval((ert-run-tests-batch-and-exit))
  command-line-1(("-l" "package" "--eval" "(add-to-list 'package-direc
  command-line()
  normal-top-level()
Test lsp-file-watch--relative-path-glob-patterns condition:
    (ert-test-failed
     ((should
       (equal expected-events events))
      :form
      (equal
       ((changed "/tmp/common-test-dir/file.ext")
        (created "/tmp/common-test-dir/file.ext"))
       nil)
      :value nil :explanation
      (different-types
       ((changed "/tmp/common-test-dir/file.ext")
        (created "/tmp/common-test-dir/file.ext"))
       nil)))
   FAILED  16/16  lsp-file-watch--relative-path-glob-patterns
```

I'm trying to understand this myself, but maybe you have a hint? I'm using the tagged 5.0 commit. The tests execute in a minimal Debian chroot environment with just elpa-f and dh-make-elpa as build requirements.

**Comment by yyoncho** [comment]
One more thing, in case you have `file-notify--library` you should run the tests with the following command: 

`cask exec ert-runner --no-win -t no-win && echo passing`

**Comment by thkoch2001** [comment]
Please re-open this issue. Emacs on Debian is compiled with inotify support. The variable `file-notify--library` is set as soon as `(require 'filenotify)` got executed.

The tests get executed with this command (not via Cask):

```
emacs -batch -Q -l package \
--eval (add-to-list 'package-directory-list "/usr/share/emacs/site-lisp/elpa") \
--eval (add-to-list 'package-directory-list "/usr/share/emacs/site-lisp/elpa-src") \
-f package-initialize -L . -L test \
-l test/lsp-mode-test.el \
-l test/lsp-file-watch-test.el \
-l test/lsp-methods-test.el \
-l test/lsp-common-test.el \
-l test/lsp-io-test.el \
--eval (ert-run-tests-batch-and-exit
```

I get the same 3 failed tests when executing them outside of the chroot.

When I execute the tests interactively in an emacs started normally, only one test still fails: `lsp-file-watch--relative-path`.

What operating system do the developers use? What is your value of `file-notify--library`?

BTW: I have no idea why the emacs/ert backtrace is cut at 72 characters.

**Comment by thkoch2001** [comment]
`cask exec ert-runner` shows the same failing tests as before. And I also tried to execute Cask with the exact line with --no-win as you recommended.

I'd expect that the tests somehow expect a behavior that is specific to one OS or filenotify library.

**Comment by yyoncho** [comment]
I will take a look

**Comment by yyoncho** [comment]
@thkoch2001 I pushed this CL to my fork, can you try it: https://github.com/yyoncho/lsp-mode/commit/dc5b12f7f72f60c32f9623f48499bd14aaa4f662

**Comment by yyoncho** [comment]
At this point the tests are passing on my system Linux Mint 19.1, emacs compiled from source (27.x) and using inotify `file-notify--library`. There was an issue with one of the tests, also I have increased the sit-for interval which was causing intermittent failures.

**Comment by thkoch2001** [comment]
Thank you for your effort and I'm sorry that nothing changed on my site. The same tests still fail:
[testresult.txt](https://github.com/emacs-lsp/lsp-mode/files/2583935/testresult.txt)

I'm using GNU Emacs 25.1.1 and file-notify--library is also set to inotify.

**Comment by yyoncho** [comment]
I believe that you could safely ignore these tests for now since the functionallity is used only in `lsp-java` and it is disabled by default. I will look more into it when the `lsp.el` restructuring is over and when.
