### ISSUE TITLE
ts-ls slow to insert completion because of "completionItem/resolve"

### ISSUE THREAD

**Issue by rafael-unloan** [emacs-lsp/lsp-mode#4757]
### Thank you for the bug report

- [x] I am using the latest version of `lsp-mode` related packages.
- [x] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

I noticed that particular completion items take 1.5 - 2 secs to be inserted.
I traced it down to this:

```elisp
               ;; see #3498 typescript-language-server does not provide the
               ;; proper insertText without resolving.
               (if (lsp-completion--find-workspace 'ts-ls)
                   (lsp-completion--resolve candidate)
                 candidate))
```
Pretty much 99% of the 1.5 - 2 sec latency is from `lsp-completion--resolve`
I know that this was added to support text edits (e.g. auto-imports) etc, but I wonder, how does VSCode do it and not lag for 1 - 2 secs?

https://github.com/user-attachments/assets/dca6b2c2-0538-47d4-9787-1cc4c8258ddf

### Steps to reproduce

Try inserting completion items for a Typescript project

### Expected behavior

Completion should be almost instant

### Which Language Server did you use?

ts-ls

### OS

MacOS

### Error callstack

```emacs-lisp
N/A (performance issue)
```

**Comment by kiennq** [comment]
Probably we can make the resolve item async on completion completed as well. WDYT @wyuenho?

**Comment by wyuenho** [comment]
@rafael-unloan if you trace the issue number back, you'll know this is a particular quirk of ts-ls. The reason VS Code is faster at completion is because it doesn't use a language server for Typescript, it just uses tsserver directly, which is not the same thing and does not require resolution for any insertText. In an effort to emulate tsserver's bahavior under LSP, typescript-language-server opted to [require resolution for the actual text to be inserted](https://github.com/typescript-language-server/typescript-language-server/pull/303/files#r869102064). This isn't something lsp-mode can and should optimize for, as resolving async eagerly will overwhelm ts-ls even more, and every textDocument/completion request will take 200+ms to respond if you type just a little bit faster.

The fastest Typescript server Emacs package is [tide](https://github.com/ananthakumaran/tide) as it sidesteps all this LSP overhead and language server feature mismatches. Give it a try.

**Comment by rafael-unloan** [comment]
I see, thank you for the info! I've tried before but still prefer `lsp-mode`. If I disable `(lsp-completion--resolve candidate)`, does it just mean that I don't get auto-imports?

**Comment by wyuenho** [comment]
You probably will lose a good chuck of completion candidates

https://github.com/typescript-language-server/typescript-language-server/blob/master/src/completion.ts#L133-L136

**Comment by wyuenho** [comment]
@rafael-unloan see if this snippet will make lsp completion faster

```elisp
               ;; see #3498 typescript-language-server does not provide the
               ;; proper insertText without resolving.
               (if (and (lsp-completion--find-workspace 'ts-ls)
                        lsp-enable-snippet
                        (memq (lsp:completion-item-kind?
                               (plist-get 'lsp-completion-item (text-properties-at 0 candidate)))
                              (list lsp/completion-item-kind-method
                                    lsp/completion-item-kind-function
                                    lsp/completion-item-kind-snippet)))
                   (lsp-completion--resolve candidate)
                 candidate))
```

**Comment by wyuenho** [comment]
Apologies for the earlier mix-up. I've made a PR with that snippet above, that should skip sync resolve unless for function or method completions. Auto import won't go away, the additional text edits and commands are resolved async later in the exit function.

**Comment by rafael-unloan** [comment]
Thank you @wyuenho! I'll try out https://github.com/emacs-lsp/lsp-mode/pull/4763

**Comment by rafael-unloan** [comment]
Awesome, super fast and I still get the auto-imports. Thank you
