### ISSUE TITLE
wrong type argument lsp--workspace nil

### ISSUE THREAD

**Issue by s-kostyaev** [emacs-lsp/lsp-mode#483]
**Describe the bug**
On every cursor movement after starting `lsp` in go buffer I can see error from topic header
**To Reproduce**
Register language client for https://github.com/saibing/bingo (install it first):
```elisp
(lsp-register-client
 (make-lsp-client :new-connection (lsp-stdio-connection "bingo")
                  :major-modes '(go-mode)
                  :server-id 'bingo))
```
Or use builtin go client from lsp-clients.el (bug also reproduces)
And start it in go buffer `M-x lsp`
**Expected behavior**
New client should work
**Which Language Server did you use**
bingo, sourcegraph/go-langserver (can also reproduce)
**OS**
macOS mojave
**Error callstack**
```
Debugger entered--Lisp error: (wrong-type-argument lsp--workspace nil)
  signal(wrong-type-argument (lsp--workspace nil))
  lsp-ui-sideline--run()
  #f(compiled-function () #<bytecode 0x40da4789>)()
  apply(#f(compiled-function () #<bytecode 0x40da4789>) nil)
  timer-event-handler([t 0 0 200000 nil #f(compiled-function () #<bytecode 0x40da4789>) nil idle 0])
```
[*Messages*](https://github.com/emacs-lsp/lsp-mode/files/2630359/messages.txt)

**Comment by yyoncho** [comment]
Please reopen if the issue exists. Just want to give a heads up - if you want to use `lsp.el` you should have this PR as well 
https://github.com/tigersoldier/company-lsp/pull/69

**Comment by s-kostyaev** [comment]
Your advices doesn't help. Even `xref-find-definitions` not working:
```
Debugger entered--Lisp error: (wrong-type-argument lsp--workspace nil)
  signal(wrong-type-argument (lsp--workspace nil))
  #f(compiled-function (backend identifier) #<bytecode 0x45a2a9f5>)(xref-lsp #("NewDecoder" 0 10 (face font-lock-function-name-face fontified t ref-params (:textDocument (:uri "file:///Users/feofan/projects/bingo/langserver/internal/source/module_cache.go") :position (:line 79 :character 21) :context (:includeDeclaration :json-false)) def-params (:textDocument (:uri "file:///Users/feofan/projects/bingo/langserver/internal/source/module_cache.go") :position (:line 79 :character 21)))))
  apply(#f(compiled-function (backend identifier) #<bytecode 0x45a2a9f5>) xref-lsp #("NewDecoder" 0 10 (face font-lock-function-name-face fontified t ref-params (:textDocument (:uri "file:///Users/feofan/projects/bingo/langserver/internal/source/module_cache.go") :position (:line 79 :character 21) :context (:includeDeclaration :json-false)) def-params (:textDocument (:uri "file:///Users/feofan/projects/bingo/langserver/internal/source/module_cache.go") :position (:line 79 :character 21)))))
  xref-backend-definitions(xref-lsp #("NewDecoder" 0 10 (face font-lock-function-name-face fontified t ref-params (:textDocument (:uri "file:///Users/feofan/projects/bingo/langserver/internal/source/module_cache.go") :position (:line 79 :character 21) :context (:includeDeclaration :json-false)) def-params (:textDocument (:uri "file:///Users/feofan/projects/bingo/langserver/internal/source/module_cache.go") :position (:line 79 :character 21)))))
  xref--find-xrefs(#("NewDecoder" 0 10 (face font-lock-function-name-face fontified t ref-params (:textDocument (:uri "file:///Users/feofan/projects/bingo/langserver/internal/source/module_cache.go") :position (:line 79 :character 21) :context (:includeDeclaration :json-false)) def-params (:textDocument (:uri "file:///Users/feofan/projects/bingo/langserver/internal/source/module_cache.go") :position (:line 79 :character 21)))) definitions #("NewDecoder" 0 10 (face font-lock-function-name-face fontified t ref-params (:textDocument (:uri "file:///Users/feofan/projects/bingo/langserver/internal/source/module_cache.go") :position (:line 79 :character 21) :context (:includeDeclaration :json-false)) def-params (:textDocument (:uri "file:///Users/feofan/projects/bingo/langserver/internal/source/module_cache.go") :position (:line 79 :character 21)))) nil)
  xref--find-definitions(#("NewDecoder" 0 10 (face font-lock-function-name-face fontified t ref-params (:textDocument (:uri "file:///Users/feofan/projects/bingo/langserver/internal/source/module_cache.go") :position (:line 79 :character 21) :context (:includeDeclaration :json-false)) def-params (:textDocument (:uri "file:///Users/feofan/projects/bingo/langserver/internal/source/module_cache.go") :position (:line 79 :character 21)))) nil)
  #f(compiled-function (identifier) "Find the definition of the identifier at point.\nWith prefix argument or when there's no identifier at point,\nprompt for it.\n\nIf sufficient information is available to determine a unique\ndefinition for IDENTIFIER, display it in the selected window.\nOtherwise, display the list of the possible definitions in a\nbuffer where the user can select from the list." (interactive #f(compiled-function () #<bytecode 0x4487eeb9>)) #<bytecode 0x44222771>)(#("NewDecoder" 0 10 (face font-lock-function-name-face fontified t ref-params (:textDocument (:uri "file:///Users/feofan/projects/bingo/langserver/internal/source/module_cache.go") :position (:line 79 :character 21) :context (:includeDeclaration :json-false)) def-params (:textDocument (:uri "file:///Users/feofan/projects/bingo/langserver/internal/source/module_cache.go") :position (:line 79 :character 21)))))
  apply(#f(compiled-function (identifier) "Find the definition of the identifier at point.\nWith prefix argument or when there's no identifier at point,\nprompt for it.\n\nIf sufficient information is available to determine a unique\ndefinition for IDENTIFIER, display it in the selected window.\nOtherwise, display the list of the possible definitions in a\nbuffer where the user can select from the list." (interactive #f(compiled-function () #<bytecode 0x4487efdd>)) #<bytecode 0x44222771>) #("NewDecoder" 0 10 (face font-lock-function-name-face fontified t ref-params (:textDocument (:uri "file:///Users/feofan/projects/bingo/langserver/internal/source/module_cache.go") :position (:line 79 :character 21) :context (:includeDeclaration :json-false)) def-params (:textDocument (:uri "file:///Users/feofan/projects/bingo/langserver/internal/source/module_cache.go") :position (:line 79 :character 21)))))
  xref-find-definitions(#("NewDecoder" 0 10 (face font-lock-function-name-face fontified t ref-params (:textDocument (:uri "file:///Users/feofan/projects/bingo/langserver/internal/source/module_cache.go") :position (:line 79 :character 21) :context (:includeDeclaration :json-false)) def-params (:textDocument (:uri "file:///Users/feofan/projects/bingo/langserver/internal/source/module_cache.go") :position (:line 79 :character 21)))))
  funcall-interactively(xref-find-definitions #("NewDecoder" 0 10 (face font-lock-function-name-face fontified t ref-params (:textDocument (:uri "file:///Users/feofan/projects/bingo/langserver/internal/source/module_cache.go") :position (:line 79 :character 21) :context (:includeDeclaration :json-false)) def-params (:textDocument (:uri "file:///Users/feofan/projects/bingo/langserver/internal/source/module_cache.go") :position (:line 79 :character 21)))))
  call-interactively(xref-find-definitions nil nil)
  command-execute(xref-find-definitions)
```

**Comment by s-kostyaev** [comment]
I'll try to reproduce it on `emacs -Q` with hand-loaded `lsp.el` tonight or at the weekend.

**Comment by MaskRay** [comment]
I've encountered this issue yesterday. `(wrong-type-argument lsp--workspace nil)`

After the removal of some `define-inline` functions (`lsp--make-request` etc) this may have been addressed.

**Comment by s-kostyaev** [comment]
for now base functions works, but very often I see:
```
Debugger entered: nil
  (progn (debug) (lsp--cancel-request lsp--cur-hover-request-id))
  (if lsp--cur-hover-request-id (progn (debug) (lsp--cancel-request lsp--cur-hover-request-id)))
  lsp--text-document-hover-string()
  lsp-hover()
  funcall(lsp-hover)
  (condition-case nil (funcall fn) (lsp-capability-not-supported nil))
  (closure (cl-struct-lsp-session-tags cl-struct-lsp--workspace-tags cl-struct-lsp--registered-capability-tags cl-struct-lsp-diagnostic-tags cl-struct-lsp--client-tags cl-struct-lsp--parser-tags t) (fn) (condition-case nil (funcall fn) (lsp-capability-not-supported nil)) nil)(lsp-hover)
  run-hook-wrapped((closure (cl-struct-lsp-session-tags cl-struct-lsp--workspace-tags cl-struct-lsp--registered-capability-tags cl-struct-lsp-diagnostic-tags cl-struct-lsp--client-tags cl-struct-lsp--parser-tags t) (fn) (condition-case nil (funcall fn) (lsp-capability-not-supported nil)) nil) lsp-hover)
  lsp-eldoc-function()
  apply(lsp-eldoc-function nil)
  #f(advice-wrapper :before-until #f(compiled-function (&rest args) #<bytecode 0x40cdbce1>) lsp-eldoc-function)()
  eldoc-print-current-symbol-info()
  #f(compiled-function () #<bytecode 0x400df6f3>)()
  apply(#f(compiled-function () #<bytecode 0x400df6f3>) nil)
  timer-event-handler([t 0 0 500000 nil #f(compiled-function () #<bytecode 0x400df6f3>) nil idle 0])
```
even with disabled debug
Also `lsp-ui-slideline` still broken

**Comment by yyoncho** [comment]
the debug issue was fixed by @MaskRay in https://github.com/emacs-lsp/lsp-mode/pull/487 . Can you share your lsp-related configuration?

**Comment by s-kostyaev** [comment]
Thanks. After building and installing latest lsp-mode & lsp-ui packages locally even better

**Comment by s-kostyaev** [comment]
But something went wrong:
```
Debugger entered--Lisp error: (wrong-type-argument lsp--workspace nil)
  signal(wrong-type-argument (lsp--workspace nil))
  lsp-ui-sideline--run()
  #f(compiled-function () #<bytecode 0x44985d8d>)()
  apply(#f(compiled-function () #<bytecode 0x44985d8d>) nil)
  timer-event-handler([t 0 0 200000 nil #f(compiled-function () #<bytecode 0x44985d8d>) nil idle 0])
```

**Comment by s-kostyaev** [comment]
My lsp-related config:
```elisp
(require 'lsp)
(setq lsp-response-timeout 1000)
(lsp-register-client
 (make-lsp-client :new-connection (lsp-stdio-connection "bingo")
                  :major-modes '(go-mode)
                  :server-id 'bingo))
```

**Comment by s-kostyaev** [comment]
Thanks all!
After disable `lsp-ui-slideline` it looks usable. Should I close this and open bug in `lsp-ui`?

**Comment by yyoncho** [comment]
So, have found the issue - you could workaround it by going into ~/elpa/lsp-ui*/ folder and deleting the .elc files. The problem is that `lsp-ui` got compiled against lsp-mode files and then it fails to work against lsp.el. Unfortunately, having `lsp.el` and `lsp-mode` in parallel is brittle and we will work to delete the legacy code as soon as possible.

**Comment by yyoncho** [comment]
@MaskRay to avoid that kind of issues we should remove all `define-inline` calls.

**Comment by s-kostyaev** [comment]
> you could workaround it by going into ~/elpa/lsp-ui*/ folder and deleting the .elc files

 @yyoncho thank you, it helps.

**Comment by j3kyl** [comment]
That works! ty! 



> So, have found the issue - you could workaround it by going into ~/elpa/lsp-ui*/ folder and deleting the .elc files. The problem is that `lsp-ui` got compiled against lsp-mode files and then it fails to work against lsp.el. Unfortunately, having `lsp.el` and `lsp-mode` in parallel is brittle and we will work to delete the legacy code as soon as possible.
